# Generated by Django 6.0.3 on 2026-03-26 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_ticket_configuration(apps, schema_editor):
    TicketTypeConfig = apps.get_model('tickets', 'TicketTypeConfig')
    PriorityConfig = apps.get_model('tickets', 'PriorityConfig')
    PlatformSettings = apps.get_model('tickets', 'PlatformSettings')

    for ordre, (code, label) in enumerate(
        [
            ('INCIDENT', 'Incident technique'),
            ('RECLAMATION', 'Reclamation'),
            ('DEMANDE', 'Demande de service'),
        ],
        start=1,
    ):
        TicketTypeConfig.objects.update_or_create(
            code=code,
            defaults={'label': label, 'actif': True, 'ordre': ordre},
        )

    for ordre, (code, label, delai_heures) in enumerate(
        [
            ('BASSE', 'Basse', 72),
            ('NORMALE', 'Normale', 48),
            ('HAUTE', 'Haute', 24),
            ('CRITIQUE', 'Critique', 4),
        ],
        start=1,
    ):
        PriorityConfig.objects.update_or_create(
            code=code,
            defaults={
                'label': label,
                'actif': True,
                'ordre': ordre,
                'delai_heures': delai_heures,
            },
        )

    PlatformSettings.objects.update_or_create(
        nom='default',
        defaults={'archive_after_days': 30},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='default', max_length=50, unique=True)),
                ('archive_after_days', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Parametre plateforme',
                'verbose_name_plural': 'Parametres plateforme',
            },
        ),
        migrations.CreateModel(
            name='PriorityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('delai_heures', models.PositiveIntegerField(default=24)),
            ],
            options={
                'verbose_name': 'Priorite',
                'verbose_name_plural': 'Priorites',
                'ordering': ['ordre', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TicketTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Type de ticket',
                'verbose_name_plural': 'Types de ticket',
                'ordering': ['ordre', 'label'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_archivage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='est_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Resolu'), ('CLOS', 'Clos')], default='OUVERT', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_ticket',
            field=models.CharField(choices=[('INCIDENT', 'Incident technique'), ('RECLAMATION', 'Reclamation'), ('DEMANDE', 'Demande de service')], default='INCIDENT', max_length=15),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('INFO', 'Information'), ('STATUT', 'Changement de statut'), ('ASSIGNATION', 'Assignation'), ('COMMENTAIRE', 'Commentaire'), ('ARCHIVAGE', 'Archivage')], default='INFO', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticket')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.RunPython(seed_ticket_configuration, migrations.RunPython.noop),
    ]
